export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  SIGNUP: '/signup',
  DASHBOARD: '/dashboard',
  NOTIFICATIONS: '/dashboard/notifications',
  MESSAGES: '/dashboard/messages',
  PROFILE: '/dashboard/profile',
  JOBS: '/dashboard/jobs',
  SAVED: '/dashboard/saved',
  PREMIUM: '/dashboard/premium',
  WALLET: '/dashboard/wallet',
  RECOMMENDATIONS: '/dashboard/recommendations',
  GROWTH: '/dashboard/growth',
} as const;
